/* AUTO-GENERATED by update-site.bat - do not edit by hand. */
window.PROJECTS = [
  {
    title: "2",
    description: "https://youtu.be/vZFKe9yVvPo.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/2.png"
  },
  {
    title: "Project One",
    description: "Short description of project one: what it does and the problem it solves.",
    tech: ["HTML", "CSS", "JavaScript"],
    live: "",
    github: "",
    image: "images/projects/project-1.jpg"
  },
  {
    title: "Project Two",
    description: "Short description of project two: what it does and the problem it solves.",
    tech: ["Networking", "MikroTik", "Security"],
    live: "",
    github: "",
    image: "images/projects/project-2.jpg"
  },
  {
    title: "Project Three",
    description: "Short description of project three: what it does and the problem it solves.",
    tech: ["Linux", "Backup", "Automation"],
    live: "",
    github: "",
    image: "images/projects/project-3.jpg"
  },
  {
    title: "Gemini Generated Image 8H7hyi8h7hyi8h7h",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Test3.png"
  }
];
