/* AUTO-GENERATED by update-site.bat - do not edit by hand. */
window.PROJECTS = [
  {
    title: "2",
    description: "https://youtu.be/vZFKe9yVvPo.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/2.png"
  },
  {
    title: "Bsod",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/BSOD.png"
  },
  {
    title: "Chfi S",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Chfi%20S.jpg"
  },
  {
    title: "Chfi",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/CHFI.jpg"
  },
  {
    title: "Comptia",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Comptia.png"
  },
  {
    title: "Digital Short Youtube",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Digital%20short%20youtube.jpg"
  },
  {
    title: "Digital",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Digital.jpg"
  },
  {
    title: "Etherchanel",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/ETHERCHANEL.png"
  },
  {
    title: "Hiren Boo Cd",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/hIREN%20BOO%20CD.png"
  },
  {
    title: "Jitbit",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Jitbit.png"
  },
  {
    title: "Mikrotec",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Mikrotec.png"
  },
  {
    title: "Mirza Numair",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Mirza%20Numair.jpg"
  },
  {
    title: "Network Throughput",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Network%20THROUGHPUT.png"
  },
  {
    title: "Network",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Network.png"
  },
  {
    title: "Nvidia",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Nvidia.jpg"
  },
  {
    title: "Openwisp",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Openwisp.png"
  },
  {
    title: "P2v Thumbnail",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/P2v%20Thumbnail.png"
  },
  {
    title: "Project One",
    description: "Short description of project one: what it does and the problem it solves.",
    tech: ["HTML", "CSS", "JavaScript"],
    live: "",
    github: "",
    image: "images/projects/project-1.jpg"
  },
  {
    title: "Project Two",
    description: "Short description of project two: what it does and the problem it solves.",
    tech: ["Networking", "MikroTik", "Security"],
    live: "",
    github: "",
    image: "images/projects/project-2.jpg"
  },
  {
    title: "Project Three",
    description: "Short description of project three: what it does and the problem it solves.",
    tech: ["Linux", "Backup", "Automation"],
    live: "",
    github: "",
    image: "images/projects/project-3.jpg"
  },
  {
    title: "Gemini Generated Image 8H7hyi8h7hyi8h7h",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Test3.png"
  },
  {
    title: "Ventoy Alternet",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/Ventoy%20alternet.png"
  },
  {
    title: "Winpe",
    description: "Add a short description here.",
    tech: [],
    live: "",
    github: "",
    image: "images/projects/winpe.png"
  }
];
