/* AUTO-GENERATED by update-site.bat - do not edit by hand. */
window.SOLUTIONS = [
  {
    title: "Backup \u0026 Disaster Recovery",
    description: "Reliable data backup and recovery plans so your business keeps running when things go wrong.",
    link: "",
    image: "images/solutions/backup-disaster-recovery.jpg"
  },
  {
    title: "CCTV \u0026 Surveillance",
    description: "Camera systems with remote viewing and recording, installed and maintained for you.",
    link: "",
    image: "images/solutions/cctv-surveillance.jpg"
  },
  {
    title: "Cybersecurity",
    description: "Firewalls, access control and security hardening to protect your business from threats.",
    link: "",
    image: "images/solutions/cybersecurity.jpg"
  },
  {
    title: "IT Support \u0026 AMC",
    description: "On-site and remote IT support with annual maintenance contracts for worry-free operations.",
    link: "",
    image: "images/solutions/it-support-amc.jpg"
  },
  {
    title: "Networking",
    description: "Design, installation and management of secure LAN/WAN, Wi-Fi and MikroTik-based networks.",
    link: "",
    image: "images/solutions/networking.jpg"
  }
];
