# =========================================================
# update-site.ps1
# Rebuilds the website data from your image folders:
#   images\projects\    ->  js\projects-data.js
#   images\solutions\   ->  js\solutions-data.js
# - every image = one card
# - optional <imagename>.txt holds the card text/links
# - if the .txt is missing, a template is created for you
# Run it by double-clicking update-site.bat
# =========================================================
$ErrorActionPreference = 'Stop'
$exts = '.jpg', '.jpeg', '.png', '.webp', '.gif'

function ToJson([string]$s) {
    if ($null -eq $s) { $s = '' }
    return ($s | ConvertTo-Json -Compress)
}

function Build-Data {
    param(
        [string]$Folder,      # e.g. images/projects
        [string]$VarName,     # e.g. PROJECTS
        [string]$OutFile,     # e.g. js\projects-data.js
        [string[]]$Keys       # text keys read from the .txt file
    )
    $dir = Join-Path $PSScriptRoot ($Folder -replace '/', '\')
    $out = Join-Path $PSScriptRoot $OutFile

    # Natural sort so item-2 comes before item-10
    $images = Get-ChildItem -LiteralPath $dir -File |
        Where-Object { $exts -contains $_.Extension.ToLower() } |
        Sort-Object { [regex]::Replace($_.Name, '\d+', { param($m) $m.Value.PadLeft(8, '0') }) }

    $entries = @()
    foreach ($img in $images) {
        $base = $img.BaseName
        $txt  = Join-Path $dir ($base + '.txt')

        # First time we see an image: create its details template
        if (-not (Test-Path -LiteralPath $txt)) {
            $pretty = (Get-Culture).TextInfo.ToTitleCase(($base -replace '[-_]+', ' ').ToLower())
            $lines = @()
            foreach ($k in $Keys) {
                if ($k -eq 'title') { $lines += "title: $pretty" }
                elseif ($k -eq 'description') { $lines += "description: Add a short description here." }
                else { $lines += "${k}: " }
            }
            [IO.File]::WriteAllText($txt, ($lines -join "`r`n"), (New-Object Text.UTF8Encoding $false))
            Write-Host "  + new item in ${Folder}: $($img.Name)  (edit $base.txt to add details)"
        }

        # Read "key: value" lines
        $info = @{}
        foreach ($k in $Keys) { $info[$k] = '' }
        foreach ($line in (Get-Content -LiteralPath $txt -Encoding UTF8)) {
            $i = $line.IndexOf(':')
            if ($i -gt 0) {
                $key = $line.Substring(0, $i).Trim().ToLower()
                $val = $line.Substring($i + 1).Trim()
                if ($info.ContainsKey($key)) { $info[$key] = $val }
            }
        }
        if ($info['title'] -eq '') { $info['title'] = $base }

        $props = @()
        foreach ($k in $Keys) {
            if ($k -eq 'tech') {
                $items = @($info['tech'] -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' })
                $props += "    tech: [" + (($items | ForEach-Object { ToJson $_ }) -join ', ') + "]"
            } else {
                $props += "    ${k}: " + (ToJson $info[$k])
            }
        }
        $props += "    image: " + (ToJson ($Folder + '/' + [uri]::EscapeDataString($img.Name)))
        $entries += "  {`r`n" + ($props -join ",`r`n") + "`r`n  }"
    }

    $content = "/* AUTO-GENERATED by update-site.bat - do not edit by hand. */`r`n" +
               "window.$VarName = [`r`n" + ($entries -join ",`r`n") + "`r`n];`r`n"
    [IO.File]::WriteAllText($out, $content, (New-Object Text.UTF8Encoding $false))
    Write-Host "Done: $($images.Count) item(s) -> $OutFile"
}

Build-Data -Folder 'images/projects'  -VarName 'PROJECTS'  -OutFile 'js\projects-data.js'  -Keys @('title','description','tech','live','github')
Build-Data -Folder 'images/solutions' -VarName 'SOLUTIONS' -OutFile 'js\solutions-data.js' -Keys @('title','description','link')
